name: 'reMarkable-Nuitka-Build-Action'
description: Run nuitka build for the reMarkable tablet
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  main:
    description: Name of the file to compile relative to the path argument
    required: true
  path:
    description: Folder that contains the source code to compile.
    required: false
    default: ${{ github.workspace }}
  output_dir:
    description: Output directory to use relative to the path argument
    required: false
    default: dist
  mode:
    description: Compilation mode to use
    type: choice
    required: false
    default: onefile
    options:
      - standalone
      - onefile
  lto:
    description: Use link time optimizations
    type: choice
    required: false
    default: auto
    options:
      - 'yes'
      - 'no'
      - auto
  static_libpython:
    description: Use static link library for python
    type: choice
    required: false
    default: auto
    options:
      - 'yes'
      - 'no'
      - auto
  extra_flags:
    description: Extra flags to pass to nuitka
    required: false
    default: |
      --assume-yes-for-downloads
      --warn-implicit-exceptions
      --warn-unusual-code
      --remove-output
      --enable-plugin=pylint-warnings
      --enable-plugin=upx
  run:
    description: Execute immediately after compilation
    type: boolean
    required: false
    default: false
  python_version:
    description: Python version to use
    required: false
    default: '3.12'
    type: choice
    options:
      - '3.12'
      - '3.11'
      - '3.10'
      - '3.9'
  clean_docker_cache:
    description: Clean the local docker cache before running
    required: false
    type: boolean
    default: false
  ccache_key:
    description: Key used for nuitka ccache
    required: false
    default: ${{ github.job }}-remarkable-2.15.1
runs:
  using: composite
  steps:
    - name: Nuitka ccache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/.nuitka
        key: ${{ inputs.ccache_key }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Clean old buildx cache
      if: ${{ inputs.clean_docker_cache }}
      shell: bash
      run: |
        docker buildx prune -f
        docker image prune -f
    - name: Run container
      shell: bash
      run: |
        cd "$workspace"
        docker run \
          --rm \
          --platform=linux/arm \
          -v "$src_path":/src \
          eeems/nuitka-arm-builder:bullseye-${{ inputs.python_version }} \
          bash -x <<'EOF'
            set -e
            source /opt/lib/nuitka/bin/activate
            cd /src
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
            NUITKA_CACHE_DIR="/src/.nuitka" \
            nuitka3 \
              --${{ inputs.mode }} \
              --lto=${{ inputs.lto }} \
              --static-libpython=${{ inputs.static_libpython }} \
              --output-dir="${{ inputs.output_dir }}" \
              --main="${{ inputs.main }}" \
              $(echo "${{ inputs.extra_flags }}" | tr '\n' ' ')
        EOF
      env:
        src_path: ${{ inputs.path }}
        workspace: ${{ github.workspace }}
    - uses: Eeems-Org/run-in-remarkable-action@v1
      if: ${{ inputs.run }}
      with:
        path: ${{ inputs.path }}
        fw_version: 2.15.1
        clean_cache: ${{ inputs.clean_docker_cache }}
        run: |
          find "${{ inputs.output_dir }}" -name '*.bin' \
            | xargs -rn1 \
            | while read -r bin; do
              echo "Running $(basename "$bin")"
              "$bin"
            done
