name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test for firmware ${{ matrix.fw_version }}
    strategy:
      matrix:
        fw_version:
          - 2.10.2
          - 2.15.1
          - 3.3.2
          - 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          fw_version: ${{ matrix.fw_version }}
          path: test
          main: test.py
          run: true
