name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.12']
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - uses: ./
        with:
          path: ${{ github.workspace }}/test
          main: test.py
          run: true
          python_version: ${{ matrix.python }}
